# Site settings
title: "Chun Yang"
email: canadachunyang@gmail.com
description: "A Full Stack Developer seeking for opportunities"
baseurl: ""
url: "https://cyang258.github.io/"
title_description: "Junior Web Developer with a background in Economics and passion for out-of-the-ordinary solutions while developing clean, modular code. Not only always get interested in learning new skills, but also a fast learner and logical thinker. After learned basic JavaScript from FreeCodeCamp.com 3 months ago, I found programming is really an interesting and fun thing to do. So I joined the 10 weeks course program provided by Lighthouse Labs, and i really enjoyed the study experience there. I learned HTML, CSS, JavaScript, Node.js, Express, PostgreSQL, MongoDB, React.js, Ruby on Rails during this 10 weeks program. And the most valuable skill I've learned is learning programing by myself. Now I am graduated from Lighthouse Labs and looking for a Junior Web Developer position opportunity."
title_image: "./favicons/personal_pic.jpg"
google_analytics: 
#"UA-20365477-4"
disqus_account: profile-4
github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-513c6fa83da6ec67
post_limit: 50

# Social usernames/URLs
twitter_username: 
github_username:  cyang258
instagram_username: 
reddit_username: 
linkedin_link: https://www.linkedin.com/in/chun-yang-903729157
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
